print("hello")
user_name = input("what your name?")
print(f"pleasure meeting you {user_name}, I'm dzx python clone1\ntill next time")
print("adding print line for master, when did checkout branch the last edit disappeared ...")
print("adding 2nd print line for master")